# NumPy 
NumPy is a python library for scientific computing. It provides a high-performance multidimensional array object, and tools for working with these arrays.

## 1. Array
A numpy array contains values of the same type, and is indexed by a tuple of nonnegative integers.

In [1]:
import numpy as np


In [16]:
#Rank = number of dimensions 
x=np.array([1,2,3])
print (f"Rank 1 array")
print(x)
y = np.array([[1,2,3],[4,5,6]]) 
print (f"Rank 2 array")
print(y)

Rank 1 array
[1 2 3]
Rank 2 array
[[1 2 3]
 [4 5 6]]


In [17]:
#Check datatype
print(type(x))

<class 'numpy.ndarray'>


In [18]:
#Shape = a tuple of integers giving the size of the array along each dimension
print(x.shape)
print(y.shape)

(3,)
(2, 3)


In [19]:
#Access elements using square bracket
print(x[2],x[0])
print(y[1,2], y[0,1])

3 1
6 2


In [20]:
#Change an element
b[0,1]=8
print(b)

[[1 8 3]
 [4 5 6]]


### Functions to create different types of arrays

In [21]:
# Create an array of all zeros of dimension 3*2
p = np.zeros((3,2))
p

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
# Create an array of all ones
o = np.ones((2,2))
o

array([[1., 1.],
       [1., 1.]])

In [27]:
# Create a constant array
c = np.full((2,2),3)
c

array([[3, 3],
       [3, 3]])

In [30]:
# Create an identical matrix of size 3*3
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
## Create an array of random values of 2*3 dimension
r = np.random.random((2,3))
r

array([[0.62656517, 0.22102611, 0.32323611],
       [0.08575869, 0.70737701, 0.3586349 ]])